# Use Node 20 (required for Docusaurus v3.9.1+)
image: node:20.13.1

pages:
  stage: build
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
  before_script:
    - echo 'yarn-offline-mirror ".yarn-cache/"' >> .yarnrc
    - echo 'yarn-offline-mirror-pruning true' >> .yarnrc
    - yarn install --frozen-lockfile
  script:
    - yarn build
    # ✅ Docusaurus outputs to "build/", not "dist/"
    - cp -a build/. public/
    - echo '/* /index.html 200' > public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never # No runners will run on branches other than main
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
