/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "EPIC",
  "tagline": "International Genetically Engineered Machine Competition",
  "favicon": "https://static.igem.wiki/teams/5657/navbar/logo.webp",
  "url": "https://2025.igem.wiki",
  "baseUrl": "/iit-madras/",
  "organizationName": "iit-madras",
  "projectName": "igem2025",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "showLastUpdateTime": false,
          "showLastUpdateAuthor": false,
          "breadcrumbs": false
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "https://static.igem.wiki/teams/5657/navbar/logo.webp",
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 2
    },
    "navbar": {
      "title": "EPIC",
      "logo": {
        "alt": "IIT Madras iGEM Logo",
        "src": "https://static.igem.wiki/teams/5657/navbar/logo.webp"
      },
      "items": [
        {
          "to": "/",
          "label": "HOME",
          "position": "right"
        },
        {
          "type": "dropdown",
          "label": "PROJECTS",
          "position": "right",
          "items": [
            {
              "to": "/project-overview",
              "label": "OVERVIEW"
            },
            {
              "to": "/project-description",
              "label": "DESCRIPTION"
            },
            {
              "to": "/engineering",
              "label": "ENGINEERING SUCCESS"
            },
            {
              "to": "/results",
              "label": "RESULTS"
            },
            {
              "to": "/future-directions",
              "label": "FUTURE DIRECTIONS"
            },
            {
              "to": "/contribution",
              "label": "CONTRIBUTIONS"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "WET LAB",
          "position": "right",
          "items": [
            {
              "to": "/experiments",
              "label": "EXPERIMENTS"
            },
            {
              "to": "/notebook",
              "label": "NOTEBOOK"
            },
            {
              "to": "/safety-and-security",
              "label": "SAFETY"
            },
            {
              "to": "/plant",
              "label": "PART COLLECTION"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "DRY LAB",
          "position": "right",
          "items": [
            {
              "to": "/software",
              "label": "SOFTWARE"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "HUMAN PRACTICES",
          "position": "right",
          "items": [
            {
              "to": "/human-practices",
              "label": "iHP"
            },
            {
              "to": "/education",
              "label": "Education"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "TEAM",
          "position": "right",
          "items": [
            {
              "to": "/attributions",
              "label": "ATTRIBUTIONS"
            },
            {
              "to": "/team",
              "label": "TEAM"
            }
          ]
        },
        {
          "href": "https://gitlab.igem.org/2025/iit-madras",
          "label": "GitLab",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "PROJECTS",
          "items": [
            {
              "label": "OVERVIEW",
              "to": "/project-overview"
            },
            {
              "label": "DESCRIPTION",
              "to": "/project-description"
            },
            {
              "label": "ENGINEERING SUCCESS",
              "to": "/engineering"
            },
            {
              "label": "RESULTS",
              "to": "/results"
            }
          ]
        },
        {
          "title": "LAB WORK",
          "items": [
            {
              "label": "EXPERIMENTS",
              "to": "/experiments"
            },
            {
              "label": "NOTEBOOK",
              "to": "/notebook"
            },
            {
              "label": "SAFETY",
              "to": "/safety-and-security"
            }
          ]
        },
        {
          "title": "TEAM & PRACTICES",
          "items": [
            {
              "label": "TEAM",
              "to": "/team"
            },
            {
              "label": "ATTRIBUTIONS",
              "to": "/attributions"
            },
            {
              "label": "iHP",
              "to": "/human-practices"
            },
            {
              "label": "Education",
              "to": "/education"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 IIT Madras iGEM Team. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
