/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "IIT Madras iGEM 2025",
  "tagline": "International Genetically Engineered Machine Competition",
  "favicon": "img/favicon.ico",
  "url": "https://your-docusaurus-site.example.com",
  "baseUrl": "/",
  "organizationName": "iit-madras",
  "projectName": "igem2025",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "editUrl": "https://github.com/iit-madras/igem2025/tree/main/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 2
    },
    "navbar": {
      "title": "IIT Madras iGEM 2025",
      "logo": {
        "alt": "IIT Madras Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "Team",
          "position": "right",
          "items": [
            {
              "to": "/team/",
              "label": "Team Overview"
            },
            {
              "to": "/team/members",
              "label": "Members"
            },
            {
              "to": "/team/attributions",
              "label": "Attributions"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Project",
          "position": "right",
          "items": [
            {
              "to": "/project/",
              "label": "Project Overview"
            },
            {
              "to": "/project/description",
              "label": "Description"
            },
            {
              "to": "/project/engineering",
              "label": "Engineering"
            },
            {
              "to": "/project/results",
              "label": "Results"
            },
            {
              "to": "/project/contribution",
              "label": "Contribution"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Wet Lab",
          "position": "right",
          "items": [
            {
              "to": "/wetlab/",
              "label": "Lab Overview"
            },
            {
              "to": "/wetlab/experiments",
              "label": "Experiments"
            },
            {
              "to": "/wetlab/notebook",
              "label": "Notebook"
            },
            {
              "to": "/wetlab/safety-and-security",
              "label": "Safety & Security"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Dry Lab",
          "position": "right",
          "items": [
            {
              "to": "/drylab/",
              "label": "Dry Lab Overview"
            },
            {
              "to": "/drylab/model",
              "label": "Modeling"
            },
            {
              "to": "/drylab/software",
              "label": "Software"
            },
            {
              "to": "/drylab/hardware",
              "label": "Hardware"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Engagement",
          "position": "right",
          "items": [
            {
              "to": "/engagement/",
              "label": "Engagement Overview"
            },
            {
              "to": "/engagement/human-practices",
              "label": "Human Practices"
            },
            {
              "to": "/engagement/education",
              "label": "Education"
            },
            {
              "to": "/engagement/inclusivity",
              "label": "Inclusivity"
            }
          ]
        },
        {
          "href": "https://github.com/iit-madras/igem2025",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Project",
          "items": [
            {
              "label": "Description",
              "to": "/project/description"
            },
            {
              "label": "Engineering",
              "to": "/project/engineering"
            },
            {
              "label": "Results",
              "to": "/project/results"
            }
          ]
        },
        {
          "title": "Lab Work",
          "items": [
            {
              "label": "Experiments",
              "to": "/wetlab/experiments"
            },
            {
              "label": "Notebook",
              "to": "/wetlab/notebook"
            },
            {
              "label": "Safety",
              "to": "/wetlab/safety-and-security"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/iit-madras/igem2025"
            },
            {
              "label": "iGEM",
              "href": "https://igem.org"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 IIT Madras iGEM Team. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
